export const GET_VACANCIES_REQUEST = 'GET_VACANCIES_REQUEST';
export const GET_VACANCIES_FAILURE = 'GET_VACANCIES_FAILURE';
export const GET_VACANCIES_SUCCESS = 'GET_VACANCIES_SUCCESS';

export const GET_NAMES_REQUEST = 'GET_NAMES_REQUEST';
export const GET_NAMES_FAILURE = 'GET_NAMES_FAILURE';
export const GET_NAMES_SUCCESS = 'GET_NAMES_SUCCESS';

export const CHANGE_SELECT_VALUE = 'CHANGE_SELECT_VALUE';

export const EDIT_VACANCY = 'EDIT_VACANCY';
export const ADD_VACANCY = 'ADD_VACANCY';
